<?php
/*
Template Name: politica de privacidad
*/
?>
<?php get_header(); ?>
<?php include ('header_retail.php'); ?>

<section class="politica">
  <div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1>POL&Iacute;TICA DE PRIVACIDAD DE CLIP</h1>
            <h3>POL&Iacute;TICA DE PRIVACIDAD DE LA EMPRESA “PAYCLIP S. DE R.L. de C.V.”</h3>
            <p>La presente Política de Privacidad describe la información que Clip recopila sobre ti, la forma en que nosotros usamos y compartimos esa información y las opciones de privacidad que nosotros ofrecemos. La presente política aplica a la información que nosotros recopilamos cuando tú te registras en Clip, accedes o usas nuestro sitio web, nuestras aplicaciones móviles, nuestros productos y servicios (en forma conjunta, los “Servicios”) o cuando tú interactúas con nosotros de otro modo. Con el fin de tener claridad, la presente política aplica a la información que nosotros recopilamos si tú haces un pago a través de los Servicios de Clip, incluso si tú no te has registrado para tener una Cuenta Clip o si no has descargado una de nuestras aplicaciones. No obstante, la presente Política de Privacidad no describe las prácticas de otros usuarios de Clip, incluidos los comerciantes que pueden recopilar información acerca de ti cuando tú interactúas con ellos a través de los Servicios, y nosotros te exhortamos a que les preguntes sobre sus prácticas de privacidad antes de proporcionarles cualquier información.<br /><br />Nosotros podemos cambiar la presente Política de Privacidad de tiempo en tiempo. Si nosotros hacemos cambios, te notificaremos por medio de la publicación de la política actualizada y la revisión de la fecha de la “Última Actualización” indicada anteriormente. Te exhortamos a que revises la Política de Privacidad siempre que uses nuestros Servicios para que permanezcas informado sobre nuestras prácticas de información y las maneras en que tú puedes ayudar a proteger tu privacidad. </p>
            <h3>RESPONSABLE DE LOS DATOS PERSONALES.</h3>
            <p>Que Clip es una sociedad mexicana constituida legalmente de conformidad a las leyes de los Estados Unidos Mexicanos, según consta en la escritura pública número 721, de fecha 26 de Julio de 2012, otorgada ante la fe de Fernando Abraham Barrita Chagoya, corredor público número 8 del Distrito Federal, cuyo primer testimonio quedó inscrito en el registro público de comercio del Distrito Federal, bajo el folio mercantil número 477428. Con domicilio en Calle Mazarik número 111 piso uno, en la Colonia Polanco Delegación Miguel Hidalgo, en México Distrito Federal. </p>
            <h3>INFORMACION A RECABAR.</h3>
            <p class="naranja"></p>
            <p>La Información que Tú Proporcionas. Nosotros recopilamos la información que tú proporcionas, como cuando te registras para tener una Cuenta Clip, cuando proporcionas información como parte de nuestro proceso de verificación de identidad o en el curso de una transacción. Nosotros podemos recopilar, aunque no estamos limitados a recopilar, lo siguiente: información básica del usuario, como tu nombre, dirección de correo electrónico, dirección postal, número de teléfono, fotografía y fecha de nacimiento, así como información financiera, incluidos los números de cuenta bancaria y de tarjeta de pago y otra información del historial, contacto y demográfica.<br /><br />También recopilamos información cuando tú subes información a los Servicios acerca de tus productos y servicios (incluidos los datos de inventarios y precios), cuando participas en los concursos o las promociones que ofrece Clip o que nuestros socios ofrecen, cuando respondes nuestras encuestas o cuando te comunicas de otro modo con nosotros.<br /><br />La Información que Nosotros Recopilamos de Tu Uso de los Servicios<br /><br />Nosotros recopilamos información sobre ti cuando tú usas nuestros Servicios, incluida la siguiente:</p>
            <ul>
            	<li>Información de Transacción. Cuando tú usas nuestros Servicios para hacer o aceptar pagos, nosotros recopilamos información sobre cuándo y dónde ocurre la transacción, una descripción de las transacciones, las cantidades de pago e información sobre los dispositivos y métodos de pago utilizados para completar las transacciones.</li>
                <li>Información de Ubicación. Cuando una de nuestras aplicaciones está abierta en tu dispositivo móvil, nosotros recibimos información en forma periódica acerca de la ubicación del dispositivo. Nosotros también podemos recopilar información de ubicación acerca de tu dispositivo si tú estás cerca de un comerciante de Clip con quien tienes una pestaña abierta. Para obtener más información, por favor consulta “Tus Opciones de Privacidad” a continuación.</li>
                <li>Información de Dispositivo. Nosotros recopilamos información de dispositivo específica cuando tú accedes a nuestros Servicios, incluido tu modelo de hardware, sistema operativo y versión, identificadores de dispositivo único, información de red móvil e información acerca de la interacción del dispositivo con nuestros Servicios. Nosotros también podemos identificar otro software activo en el dispositivo (pero no recopilaremos ningún contenido de dicho software) con el propósito de prevenir fraudes y programas malignos (malware).</li>
                <li>Información de Uso. Nosotros recopilamos información acerca de la manera en que tú usas nuestros Servicios, incluidos tus tiempos de acceso, tipos de navegador e idioma y direcciones de Protocolo de Internet (“IP”, por sus siglas en inglés).</li>
                <li>La Información que Recopilan las Cookies y los Web Beacons. Nosotros usamos varias tecnologías para recopilar información, las cuales pueden incluir el envío de cookies a tu computadora o dispositivo móvil. Las cookies son pequeños archivos de datos que se almacenan en tu disco duro o en la memoria de un dispositivo por medio de un sitio web. Entre otras cosas, las cookies soportan la integridad de nuestro proceso de registro, retienen tus preferencias y configuraciones de cuenta, además de que ayudan a evaluar y compilar estadísticas agregadas acerca de la actividad del usuario. Nosotros también podemos recopilar información utilizando web beacons. Los web beacons son imágenes electrónicas que se pueden usar en nuestros Servicios o en correos electrónicos. Nosotros podemos usar web beacons para entregar cookies, contar visitas, entender el uso y la efectividad de las campañas, así como para determinar si un correo electrónico se ha abierto y ha influido.</li>
            </ul>
            <p class="naranja">A continuación se presentan ejemplos de datos que podrán solicitarse:</p>
            <p>TRATANDOSE DE PERSONAS FISICAS. Nombre, sexo, dirección, teléfonos de contacto,(casa, oficina, y celular), correo electrónico, edad, fecha de nacimiento, referencias personales, ocupación, nacionalidad, país de nacimiento, estado civil, Constancia única de Registro de Población, Registro Federal de Contribuyentes, nombre de la empresa donde ha laborado, puesto, antigüedad laborando en la empresa, fuente de ingresos, números de cuenta, en instituciones bancarias para efectos de pagos, clabe interbancaria, Numero de Seguridad Social, escolaridad, Dependientes económicos, Datos del Cónyuge, información Financiera, Declaración de salud entre otros independientemente de los mencionados en el presente documento.<br /><br />TRATANDOSE DE PERSONAS MORALES. Acta constitutiva, o documento que acredite la legal existencia de la sociedad, debidamente registrada, Modificación del acta constitutiva (en su caso) poder del representante legal con datos del registro, identificación del registro legal, alta en hacienda, RFC de la Sociedad, Comprobante de domicilio, alta patronal ante el IMSS, Clabe Interbancaria, Información Financiera, Referencias Bancarias, entre otras ya mencionadas en el presente documento.</p>
            <h3>La Información que Nosotros Recopilamos de Otras Fuentes</h3>
            <p>Nosotros también podemos recopilar información sobre ti por parte de terceros, incluidos sin limitación los servicios de verificación de terceros, burós de crédito, proveedores de listas de correo y fuentes disponibles para el público. Esta información puede incluir tu Número de Seguro Social.</p>
            <h3>Publicidad y Analítica de Terceros</h3>
            <p>Nosotros podemos permitirle a terceros que presenten anuncios en relación con nuestros Servicios y que provean servicios de analítica. Estos terceros pueden usar cookies, web beacons y otras tecnologías para recopilar información como tus direcciones IP, identificadores asociados con tu dispositivo móvil o aplicaciones del dispositivo, los navegadores que usas para visitar nuestros Servicios, las páginas vistas, el tiempo invertido en las páginas, los vínculos en los que haces clic y la información de conversión. Clip y otras compañías pueden usar esta información para analizar y rastrear datos, determinar la popularidad de cierto contenido, entregar publicidad y contenido dirigido a tus intereses y entender mejor tu uso. La presente Política de Privacidad no aplica a, y nosotros no somos responsables de, cookies, web beacons ni otras tecnologías de rastreo de terceros, y nosotros te exhortamos a revisar las políticas de privacidad de dichos terceros para que sepas más acerca de sus prácticas de privacidad. Para obtener más información sobre la publicidad dirigida específicamente, o para que elijas que la información de tu navegador no se use con éstos propósitos, visita los sitios http://www.aboutads.info/choices y http://www.networkadvertising.org/managing/opt_out.asp.</p>
            <h3>Uso de la Información</h3>
            <p>Nosotros usamos la información sobre ti para proporcionar, dar mantenimiento y mejorar nuestros Servicios, así como para entregar la información y el soporte que tú solicitas, incluidos los recibos, las notificaciones técnicas, alertas de seguridad y mensajes tanto de soporte como administrativos. <br /><br />Nosotros también usamos la información sobre ti para mejorar y personalizar los Servicios. Sólo para dar un ejemplo, cuando tú te registras para tener una Cuenta Clip, nosotros podemos asociar cierta información con tu nueva cuenta, como la información acerca de otras cuentas que tú tienes o tuviste con Clip y las transacciones anteriores que tú hiciste a través de los Servicios de Clip.<br /><br />Nosotros podemos usar la información que recopilamos para enviarte noticias e información acerca de nuestros Servicios y para comunicarnos contigo dándote información sobre productos, servicios, concursos, promociones, incentivos y recompensas que nosotros y nuestros socios selectos ofrecemos.<br /><br />Nosotros también podemos usar la información acerca de ti para rastrear y analizar las tendencias y el uso en relación con nuestros Servicios, para procesar y entregar boletos y recompensas de concursos y promociones, para proteger nuestros derechos o nuestra propiedad, para verificar tu identidad, para investigar y evitar fraudes u otras actividades ilegales y para cualquier otro propósito que se divulgue a ti en relación con nuestros Servicios.<br /><br />Nosotros podemos usar proveedores de servicios de terceros para, procesar y almacenar información personal en los Estados Unidos Mexicanos y otros países.</p>
            <h3>Información Compartida</h3>
            <p class="naranja">Nosotros podemos compartir la información personal acerca de ti como sigue:</p>
            <ul>
            	<li>Con terceros para proporcionar, dar mantenimiento y mejorar nuestros Servicios, incluidos los proveedores de servicios que tienen acceso a la información sobre ti para prestar servicios en nuestro nombre (esto es, servicios de prevención de fraudes y de verificación) e incluidas las instituciones financieras, procesadores, asociaciones de tarjetas de pago y otras entidades que son parte del proceso de pago;</li>
                <li>Con otras personas que se han registrado para tener Cuentas Clip. Por ejemplo, nosotros podemos compartir información cuando tú haces o aceptas un pago utilizando nuestros Servicios. Nosotros también podemos compartir información acerca de ti cuando estás cerca de un comerciante de Clip con quien tienes una pestaña abierta;</li>
                <li>Con terceros que llevan a cabo campañas de publicidad, concursos, ofertas especiales u otros eventos o actividades en relación con nuestros Servicios;</li>
                <li>En relación con, o durante la negociación de, cualquier fusión, venta de acciones o activos de la compañía, financiamiento, adquisición, desinversión o disolución de todo o parte de nuestro negocio;</li>
                <li>Si nosotros creemos que la divulgación es razonablemente necesaria para cumplir con cualquier ley, reglamentación, proceso legal o requisito gubernamental aplicable, para ejecutar convenios o políticas de usuario aplicables, para proteger la seguridad o integridad de nuestros Servicios y para protegernos y proteger a nuestros usuarios o al público contra daños o actividades ilegales; y</li>
                <li>Con tu consentimiento.</li>
            </ul>
            <p>Nosotros también podemos compartir con terceros la información agregada que no permite la identificación personal</p>
            <h3>MEDIOS PARA EL EJERCICIO DE DERECHOS DEL TITULAR.</h3>
            <p>El titular de datos personales, podrá ejercer su derecho ARCO (acceso, rectificación, cancelación, oposición), limitación de uso, divulgación, o revocación, por correo al siguiente domicilio, ______ con atención al Comité, mediante solicitud por escrito que contenga la siguiente información, I. nombre completo del titular de los datos, personales, domicilio y cuenta de correo electrónico, para poder comunicarle la respuesta a su solicitud. II. Los documentos que acrediten la identidad y en su caso la representación, legal del titular, de los datos personales. III. La descripción clara y precisa de los datos personales respecto de los que se buscan ejercer alguno de los derechos antes mencionados, IV. Cualquier otro elemento o documento que facilite la localización de los datos personales. V. en caso de solicitud de rectificaciones de datos personales, el titular deberá indicar las modificaciones a realizarse y aportar la documentación que sustente su petición. O bien al siguiente correo electrónico. <a href="mailto:privacidad@clip.mx">privacidad@clip.mx</a><br /><br />El tiempo de respuesta a las solicitudes presentadas será de veinte días hábiles máximo y de quince días para hacer efectivo el ejercicio del derecho ARCO, que se solicite.<br /><br />No obstante dichos términos podrán duplicarse cuando existan hechos que lo justifiquen.</p>
            <h3>Seguridad</h3>
            <p>Nosotros tomamos medidas razonables, incluidas las salvaguardas administrativas, técnicas y físicas, para ayudar a proteger la información personal contra pérdida, robo, mal uso y acceso no autorizado, divulgación, alteración y destrucción. </p>
            <h3>Tus Opciones de Privacidad</h3>
            <p class="naranja">Información Personal</p>
            <p>Tú puedes actualizar o corregir la información sobre ti al entrar a tu cuenta en cualquier momento o al enviarnos un correo electrónico a <a href="mailto:privacidad@clip.mx">privacidad@clip.mx</a>. Tú también puedes enviarnos un correo electrónico si deseas desactivar tu cuenta, pero incluso después de que hayas desactivado tu cuenta, nosotros podremos conservar las copias archivadas de la información acerca de ti y de tus transacciones durante un periodo que sea consistente con la ley aplicable.</p>
            <p class="naranja">Información de Ubicación</p>
            <p>Cuando tú activas por primera vez cualquiera de nuestras aplicaciones móviles, se te solicitará tu consentimiento para que la aplicación recopile la información de ubicación. En la actualidad, nosotros solicitamos esta información de ubicación con el fin de prestar nuestros Servicios, así que si tú no das tu consentimiento para esta recopilación, no podrás usar nuestros Servicios. Si en un principio das tu consentimiento para que nosotros recopilemos la información de ubicación, de manera posterior tú podrás detener nuestra recopilación de la información de ubicación en cualquier momento al cambiar las preferencias en tu dispositivo móvil. Si tú haces esto, la aplicación de Clip ya no funcionará. Tú también puedes detener nuestra recopilación de la información de ubicación al realizar el proceso de desinstalación estándar para eliminar todas las aplicaciones de Clip de tu dispositivo.</p>
            <p class="naranja">Cookies</p>
            <p>La mayoría de los navegadores de Internet están configurados para aceptar cookies en forma predeterminada. Si así lo prefieres, por lo general tú puedes configurar tu navegador para eliminar o rechazar cookies; sin embargo, quizá nuestros Servicios no funcionen de manera apropiada si lo haces. </p>
            <p class="naranja">Comunicados sobre Promociones</p>
            <p>Tú puedes elegir no recibir correos electrónicos o mensajes de texto con promociones de Clip al seguir las instrucciones incluidas en tales correos electrónicos o mensajes de texto. Si eliges no recibirlos, aun así nosotros podemos enviarte comunicados no promocionales como mensajes acerca de tu cuenta o nuestras relaciones de negocios continuas.</p>
            <p class="naranja">Contacto</p>
            <p>Por favor contacta a nuestro Departamento de Privacidad si tienes preguntas o inquietudes relacionadas con nuestra política en el 01800 00 CLIPMX o en <a href="mailto:privacidad@clip.mx">privacidad@clip.mx</a></p>
            <p class="naranja">Política de Correo Electrónico</p>
            <h3>CAMBIOS AL AVISO DE PRIVACIDAD.</h3>
            <p>Cualquier cambio a la presente política de privacidad, le serán informados a través de cualquiera de los siguientes medios: Avisos en el sitio web www.clip.mx” y Correo electrónico por medio de <a href="mailto:privacidad@clip.mx">privacidad@clip.mx</a><br /><br />Cualquier otro medio de comunicación público o privado previsto en los contratos que amparan las operaciones celebradas por CLIP. </p>
    </div>
  </div>
</section>

<?php get_footer(); ?>